apiVersion: v1
data:
  NODE_ENV: TEST
  PORT: "80"
  environment: test
kind: ConfigMap
metadata:
  labels:
    app: demo-website
    group: demo-website
  name: test-demo-website
---
apiVersion: v1
data:
  config.js: |-
    var config = {
        DEPLOYMENT_ENV: "TEST",
    };
kind: ConfigMap
metadata:
  labels:
    app: demo-website
    group: demo-website
  name: test-website-config-85fk47tbf7
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-website
    group: demo-website
    name: demo-website-http
  name: test-demo-website-http
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: demo-website
    group: demo-website
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-website
    group: demo-website
  name: test-demo-website-loadbalancer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-website
    group: demo-website
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-website
    group: demo-website
  name: test-demo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-website
      group: demo-website
  template:
    metadata:
      labels:
        app: demo-website
        group: demo-website
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: test-demo-website
        image: mazgis47/test-web-app:latest
        name: demo-website
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
